### ISSUE TITLE
Maybe we could put some optional service-worker for progressive webapps.

### ISSUE THREAD

**Issue by leodsgn** [pedsmoreira/premiere#1]
After reading about the google specifications, I think we could work more with cache and service-workers for offline applications.

We could put it as optional feature.

For more detailed info about service-workers, take a look at [google specification](https://developers.google.com/web/fundamentals/getting-started/primers/service-workers?authuser=2) and [mozilla specifications](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers).

What do you thinks about it?

**Comment by pedsmoreira** [comment]
I think this could be a good idea, but could add a whole new level of complexity to the library.

If you find a good way to implement without too much extra complexity, feel free to open a PR. Perhaps this could also be a new library.

Thanks for the suggestion
